### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by TaWald** [MrGiovanni/SuPreM#4]
Hello,

I want to congratulate you on your nice work! 
It is really impressive. 
Would you be so kind to point me to where the CT data and annotations you created are available?

Best regards,
Tassilo Wald

**Comment by MrGiovanni** [comment]
Hi @TaWald

Thanks for your interest in our work.

We are pushing the data review process for AbdomenAtlas 1.1, and anticipate **fully** releasing the dataset to the public on 5/7/2024 (ICLR Conference Day).

Before the official release, AbdomenAtlas 1.1 will be used for the [**ISBI BodyMaps 2024**](https://codalab.lisn.upsaclay.fr/competitions/16919). If you're interested in early access to this dataset, feel free to participate. 😃 

Besides, there is a previous version called [**AbdomenAtlas 1.0**](https://www.dropbox.com/scl/fi/890cavm8n3pjyyy5df2lk/AbdomenAtlasMini1.0.tar.gz?rlkey=8d53plsdojlf9hjqqddbyfeb0&dl=0) [1] While this dataset is relatively small and has fewer annotated classes, it could be a good starting point for "supervised pre-training" models as **strongly** recommended in our new study [2].

Hope it helps.

Best,
Wenxuan & Zongwei

[1] Qu, Chongyu, Tiezheng Zhang, Hualin Qiao, Jie Liu, Yucheng Tang, Alan Yuille, and Zongwei Zhou. "Abdomenatlas-8k: Annotating 8,000 CT volumes for multi-organ segmentation in three weeks." In *Thirty-seventh Conference on Neural Information Processing Systems Datasets and Benchmarks Track*. 2023. https://www.cs.jhu.edu/~alanlab/Pubs23/qu2023abdomenatlas.pdf

[2] Li, Wenxuan, Alan Yuille, and Zongwei Zhou. "How Well Do Supervised 3D Models Transfer to Medical Imaging Tasks?" In *International Conference on Learning Representations*. 2024. https://www.cs.jhu.edu/~alanlab/Pubs23/li2023suprem.pdf

**Comment by lotfi-hku** [comment]
Thank you once again for your invaluable work.
It's past May 7th and the ICLR conference has just finished.
Has your plan to release the version 1.1 of the dataset changed?

**Comment by WenxuanChelsea** [comment]
Hi @lotfi-hku

Thanks for your interest in our dataset.

The release of AbdomenAtlas 1.1 is currently on hold due to data permission issues, particularly with CT volumes from the [RSNA Abdominal Trauma Detection](https://www.kaggle.com/competitions/rsna-2023-abdominal-trauma-detection/overview) (which accounts for 4,067 CT volumes; 44%). They have [very strict rules](https://www.kaggle.com/competitions/rsna-2023-abdominal-trauma-detection/rules) for data re-distribution. Direct quote as follows:
> DATA ACCESS AND USE: Non-Commercial Use, for the purposes of the competition. Re-distribution or re-identification of any data is strictly prohibited.

We have been actively negotiating with the RSNA committees for the past four months but have not yet received re-distribution permission, and further delays may occur.

You can access **the rest of** the AbdomenAtlas 1.1 dataset (5,195 CT volumes, 25 annotated classes) by participating in the BodyMaps Challenge at MICCAI 2024. Please stay tuned!

Thanks,
Wenxuan

**Comment by lotfi-hku** [comment]
Thanks @WenxuanChelsea 

Have you released the rest of the AbdomenAtlas 1.1 dataset (5,195 CT volumes) anywhere yet?
I couldn't find it either in in [MICCAI 2024 BodyMap](https://zenodo.org/records/10992089) or in [ISBI BodyMaps24](https://codalab.lisn.upsaclay.fr/competitions/16919).
